---
title: "Project_Code"
subtitle: "https://github.com/lhr12"
author: "Lindsay Roth"
date: "4/3/2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
```{r load packages}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(dplyr)
library(viridis)
library(RColorBrewer)
library(colormap)
library(nlme)
library(lsmeans)
library(multcompView)
library(trend)
library(mapview)
library(leaflet)
library(sf)

mytheme <- theme_classic(base_size = 12) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top", 
        legend.key.size = unit(0.5, "cm"))
theme_set(mytheme)

#setwd("~/Documents/MEM 1st Year/Spring 2019/Env_Data_Analytics/ENV_Data_Analytics_Project")
```

```{r download data files}
O3_1980 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1980_Raw.csv")
O3_1981 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1981_Raw.csv")
O3_1982 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1982_Raw.csv")
O3_1983 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1983_Raw.csv")
O3_1984 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1984_Raw.csv")
O3_1985 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1985_Raw.csv")
O3_1986 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1986_Raw.csv")
O3_1987 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1987_Raw.csv")
O3_1988 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1988_Raw.csv")
O3_1989 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1989_Raw.csv")
O3_1990 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1990_Raw.csv")
O3_1991 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1991_Raw.csv")
O3_1992 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1992_Raw.csv")
O3_1993 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1993_Raw.csv")
O3_1994 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1994_Raw.csv")
O3_1995 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1995_Raw.csv")
O3_1996 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1996_Raw.csv")
O3_1997 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1997_Raw.csv")
O3_1998 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1998_Raw.csv")
O3_1999 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles1999_Raw.csv")
O3_2000 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2000_Raw.csv")
O3_2001 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2001_Raw.csv")
O3_2002 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2002_Raw.csv")
O3_2003 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2003_Raw.csv")
O3_2004 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2004_Raw.csv")
O3_2005 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2005_Raw.csv")
O3_2006 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2006_Raw.csv")
O3_2007 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2007_Raw.csv")
O3_2008 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2008_Raw.csv")
O3_2009 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2009_Raw.csv")
O3_2010 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2010_Raw.csv")
O3_2011 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2011_Raw.csv")
O3_2012 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2012_Raw.csv")
O3_2013 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2013_Raw.csv")
O3_2014 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2014_Raw.csv")
O3_2015 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2015_Raw.csv")
O3_2016 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2016_Raw.csv")
O3_2017 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2017_Raw.csv")
O3_2018 <- read.csv("./Data/Raw/EPAair_O3_LosAngeles2018_Raw.csv")
```

```{r fix dates}

O3_1980$Date <- as.Date(O3_1980$Date, format = "%m/%d/%Y")
O3_1981$Date <- as.Date(O3_1981$Date, format = "%m/%d/%Y")
O3_1982$Date <- as.Date(O3_1982$Date, format = "%m/%d/%Y")
O3_1983$Date <- as.Date(O3_1983$Date, format = "%m/%d/%Y")
O3_1984$Date <- as.Date(O3_1984$Date, format = "%m/%d/%Y")
O3_1985$Date <- as.Date(O3_1985$Date, format = "%m/%d/%Y")
O3_1986$Date <- as.Date(O3_1986$Date, format = "%m/%d/%Y")
O3_1987$Date <- as.Date(O3_1987$Date, format = "%m/%d/%Y")
O3_1988$Date <- as.Date(O3_1988$Date, format = "%m/%d/%Y")
O3_1989$Date <- as.Date(O3_1989$Date, format = "%m/%d/%Y")
O3_1990$Date <- as.Date(O3_1990$Date, format = "%m/%d/%Y")
O3_1991$Date <- as.Date(O3_1991$Date, format = "%m/%d/%Y")
O3_1992$Date <- as.Date(O3_1992$Date, format = "%m/%d/%Y")
O3_1993$Date <- as.Date(O3_1993$Date, format = "%m/%d/%Y")
O3_1994$Date <- as.Date(O3_1994$Date, format = "%m/%d/%Y")
O3_1995$Date <- as.Date(O3_1995$Date, format = "%m/%d/%Y")
O3_1996$Date <- as.Date(O3_1996$Date, format = "%m/%d/%Y")
O3_1997$Date <- as.Date(O3_1997$Date, format = "%m/%d/%Y")
O3_1998$Date <- as.Date(O3_1998$Date, format = "%m/%d/%Y")
O3_1999$Date <- as.Date(O3_1999$Date, format = "%m/%d/%Y")
O3_2000$Date <- as.Date(O3_2000$Date, format = "%m/%d/%Y")
O3_2001$Date <- as.Date(O3_2001$Date, format = "%m/%d/%Y")
O3_2002$Date <- as.Date(O3_2002$Date, format = "%m/%d/%Y")
O3_2003$Date <- as.Date(O3_2003$Date, format = "%m/%d/%Y")
O3_2004$Date <- as.Date(O3_2004$Date, format = "%m/%d/%Y")
O3_2005$Date <- as.Date(O3_2005$Date, format = "%m/%d/%Y")
O3_2006$Date <- as.Date(O3_2006$Date, format = "%m/%d/%Y")
O3_2007$Date <- as.Date(O3_2007$Date, format = "%m/%d/%Y")
O3_2008$Date <- as.Date(O3_2008$Date, format = "%m/%d/%Y")
O3_2009$Date <- as.Date(O3_2009$Date, format = "%m/%d/%Y")
O3_2010$Date <- as.Date(O3_2010$Date, format = "%m/%d/%Y")
O3_2011$Date <- as.Date(O3_2011$Date, format = "%m/%d/%Y")
O3_2012$Date <- as.Date(O3_2012$Date, format = "%m/%d/%Y")
O3_2013$Date <- as.Date(O3_2013$Date, format = "%m/%d/%Y")
O3_2014$Date <- as.Date(O3_2014$Date, format = "%m/%d/%Y")
O3_2015$Date <- as.Date(O3_2015$Date, format = "%m/%d/%Y")
O3_2016$Date <- as.Date(O3_2016$Date, format = "%m/%d/%Y")
O3_2017$Date <- as.Date(O3_2017$Date, format = "%m/%d/%Y")
O3_2018$Date <- as.Date(O3_2018$Date, format = "%m/%d/%Y")

```

```{r summaries by year}
O3_1980_summary <- O3_1980 %>%
  mutate(Year = year(O3_1980$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1981_summary <- O3_1981 %>%
  mutate(Year = year(O3_1981$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1982_summary <- O3_1982 %>%
  mutate(Year = year(O3_1982$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1983_summary <- O3_1983 %>%
  mutate(Year = year(O3_1983$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1984_summary <- O3_1984 %>%
  mutate(Year = year(O3_1984$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1985_summary <- O3_1985 %>%
  mutate(Year = year(O3_1985$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1986_summary <- O3_1986 %>%
  mutate(Year = year(O3_1986$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1987_summary <- O3_1987 %>%
  mutate(Year = year(O3_1987$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1988_summary <- O3_1988 %>%
  mutate(Year = year(O3_1988$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1989_summary <- O3_1989 %>%
  mutate(Year = year(O3_1989$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1990_summary <- O3_1990 %>%
  mutate(Year = year(O3_1990$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1991_summary <- O3_1991 %>%
  mutate(Year = year(O3_1991$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1992_summary <- O3_1992 %>%
  mutate(Year = year(O3_1992$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1993_summary <- O3_1993 %>%
  mutate(Year = year(O3_1993$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1994_summary <- O3_1994 %>%
  mutate(Year = year(O3_1994$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1995_summary <- O3_1995 %>%
  mutate(Year = year(O3_1995$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1996_summary <- O3_1996 %>%
  mutate(Year = year(O3_1996$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1997_summary <- O3_1997 %>%
  mutate(Year = year(O3_1997$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1998_summary <- O3_1998 %>%
  mutate(Year = year(O3_1998$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1999_summary <- O3_1999 %>%
  mutate(Year = year(O3_1999$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2000_summary <- O3_2000 %>%
  mutate(Year = year(O3_2000$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2001_summary <- O3_2001 %>%
  mutate(Year = year(O3_2001$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2002_summary <- O3_2002 %>%
  mutate(Year = year(O3_2002$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2003_summary <- O3_2003 %>%
  mutate(Year = year(O3_2003$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2004_summary <- O3_2004 %>%
  mutate(Year = year(O3_2004$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2005_summary <- O3_2005 %>%
  mutate(Year = year(O3_2005$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2006_summary <- O3_2006 %>%
  mutate(Year = year(O3_2006$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2007_summary <- O3_2007 %>%
  mutate(Year = year(O3_2007$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2008_summary <- O3_2008 %>%
  mutate(Year = year(O3_2008$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2009_summary <- O3_2009 %>%
  mutate(Year = year(O3_2009$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2010_summary <- O3_2010 %>%
  mutate(Year = year(O3_2010$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2011_summary <- O3_2011 %>%
  mutate(Year = year(O3_2011$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2012_summary <- O3_2012 %>%
  mutate(Year = year(O3_2012$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2013_summary <- O3_2013 %>%
  mutate(Year = year(O3_2013$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2014_summary <- O3_2014 %>%
  mutate(Year = year(O3_2014$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2015_summary <- O3_2015 %>%
  mutate(Year = year(O3_2015$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2016_summary <- O3_2016 %>%
  mutate(Year = year(O3_2016$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2017_summary <- O3_2017 %>%
  mutate(Year = year(O3_2017$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2018_summary <- O3_2018 %>%
  mutate(Year = year(O3_2018$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))

```

```{r summaries by month}
O3_1980_summary_month <- O3_1980 %>%
  mutate(Year = year(O3_1980$Date)) %>%
  mutate(Month = month(O3_1980$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1981_summary_month <- O3_1981 %>%
  mutate(Year = year(O3_1981$Date)) %>%
  mutate(Month = month(O3_1981$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1982_summary_month <- O3_1982 %>%
  mutate(Year = year(O3_1982$Date)) %>%
  mutate(Month = month(O3_1982$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1983_summary_month <- O3_1983 %>%
  mutate(Year = year(O3_1983$Date)) %>%
  mutate(Month = month(O3_1983$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1984_summary_month <- O3_1984 %>%
  mutate(Year = year(O3_1984$Date)) %>%
  mutate(Month = month(O3_1984$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1985_summary_month <- O3_1985 %>%
  mutate(Year = year(O3_1985$Date)) %>%
  mutate(Month = month(O3_1985$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1986_summary_month <- O3_1986 %>%
  mutate(Year = year(O3_1986$Date)) %>%
  mutate(Month = month(O3_1986$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1987_summary_month <- O3_1987 %>%
  mutate(Year = year(O3_1987$Date)) %>%
  mutate(Month = month(O3_1987$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1988_summary_month <- O3_1988 %>%
  mutate(Year = year(O3_1988$Date)) %>%
  mutate(Month = month(O3_1988$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1989_summary_month <- O3_1989 %>%
  mutate(Year = year(O3_1989$Date)) %>%
  mutate(Month = month(O3_1989$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1990_summary_month <- O3_1990 %>%
  mutate(Year = year(O3_1990$Date)) %>%
  mutate(Month = month(O3_1990$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1991_summary_month <- O3_1991 %>%
  mutate(Year = year(O3_1991$Date)) %>%
  mutate(Month = month(O3_1991$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1992_summary_month <- O3_1992 %>%
  mutate(Year = year(O3_1992$Date)) %>%
  mutate(Month = month(O3_1992$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1993_summary_month <- O3_1993 %>%
  mutate(Year = year(O3_1993$Date)) %>%
  mutate(Month = month(O3_1993$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1994_summary_month <- O3_1994 %>%
  mutate(Year = year(O3_1994$Date)) %>%
  mutate(Month = month(O3_1994$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1995_summary_month <- O3_1995 %>%
  mutate(Year = year(O3_1995$Date)) %>%
  mutate(Month = month(O3_1995$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1996_summary_month <- O3_1996 %>%
  mutate(Year = year(O3_1996$Date)) %>%
  mutate(Month = month(O3_1996$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1997_summary_month <- O3_1997 %>%
  mutate(Year = year(O3_1997$Date)) %>%
  mutate(Month = month(O3_1997$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1998_summary_month <- O3_1998 %>%
  mutate(Year = year(O3_1998$Date)) %>%
  mutate(Month = month(O3_1998$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1999_summary_month <- O3_1999 %>%
  mutate(Year = year(O3_1999$Date)) %>%
  mutate(Month = month(O3_1999$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2000_summary_month <- O3_2000 %>%
  mutate(Year = year(O3_2000$Date)) %>%
  mutate(Month = month(O3_2000$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2001_summary_month <- O3_2001 %>%
  mutate(Year = year(O3_2001$Date)) %>%
  mutate(Month = month(O3_2001$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2002_summary_month <- O3_2002 %>%
  mutate(Year = year(O3_2002$Date)) %>%
  mutate(Month = month(O3_2002$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2003_summary_month <- O3_2003 %>%
  mutate(Year = year(O3_2003$Date)) %>%
  mutate(Month = month(O3_2003$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2004_summary_month <- O3_2004 %>%
  mutate(Year = year(O3_2004$Date)) %>%
  mutate(Month = month(O3_2004$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2005_summary_month <- O3_2005 %>%
  mutate(Year = year(O3_2005$Date)) %>%
  mutate(Month = month(O3_2005$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2006_summary_month <- O3_2006 %>%
  mutate(Year = year(O3_2006$Date)) %>%
  mutate(Month = month(O3_2006$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2007_summary_month <- O3_2007 %>%
  mutate(Year = year(O3_2007$Date)) %>%
  mutate(Month = month(O3_2007$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2008_summary_month <- O3_2008 %>%
  mutate(Year = year(O3_2008$Date)) %>%
  mutate(Month = month(O3_2008$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2009_summary_month <- O3_2009 %>%
  mutate(Year = year(O3_2009$Date)) %>%
  mutate(Month = month(O3_2009$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2010_summary_month <- O3_2010 %>%
  mutate(Year = year(O3_2010$Date)) %>%
  mutate(Month = month(O3_2010$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2011_summary_month <- O3_2011 %>%
  mutate(Year = year(O3_2011$Date)) %>%
  mutate(Month = month(O3_2011$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2012_summary_month <- O3_2012 %>%
  mutate(Year = year(O3_2012$Date)) %>%
  mutate(Month = month(O3_2012$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2013_summary_month <- O3_2013 %>%
  mutate(Year = year(O3_2013$Date)) %>%
  mutate(Month = month(O3_2013$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2014_summary_month <- O3_2014 %>%
  mutate(Year = year(O3_2014$Date)) %>%
  mutate(Month = month(O3_2014$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2015_summary_month <- O3_2015 %>%
  mutate(Year = year(O3_2015$Date)) %>%
  mutate(Month = month(O3_2015$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2016_summary_month <- O3_2016 %>%
  mutate(Year = year(O3_2016$Date)) %>%
  mutate(Month = month(O3_2016$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2017_summary_month <- O3_2017 %>%
  mutate(Year = year(O3_2017$Date)) %>%
  mutate(Month = month(O3_2017$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2018_summary_month <- O3_2018 %>%
  mutate(Year = year(O3_2018$Date)) %>%
  mutate(Month = month(O3_2018$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Month, Year) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
```

```{r combine and process data sets}
O3_total_year <- rbind(O3_1980_summary,O3_1981_summary,O3_1982_summary,
                  O3_1983_summary,O3_1984_summary,O3_1985_summary,
                  O3_1986_summary,O3_1987_summary,O3_1988_summary,
                  O3_1989_summary,O3_1990_summary,O3_1991_summary,
                  O3_1992_summary,O3_1993_summary,O3_1994_summary,
                  O3_1995_summary,O3_1996_summary,O3_1997_summary,
                  O3_1998_summary,O3_1999_summary,O3_2000_summary,
                  O3_2001_summary,O3_2002_summary,O3_2003_summary,
                  O3_2004_summary,O3_2005_summary,O3_2006_summary,
                  O3_2007_summary,O3_2008_summary,O3_2009_summary,
                  O3_2010_summary,O3_2011_summary,O3_2012_summary,
                  O3_2013_summary,O3_2014_summary,O3_2015_summary,
                  O3_2016_summary,O3_2017_summary,O3_2018_summary)

O3_total_month <- rbind(O3_1980_summary_month,O3_1981_summary_month,O3_1982_summary_month,
                  O3_1983_summary_month,O3_1984_summary_month,O3_1985_summary_month,
                  O3_1986_summary_month,O3_1987_summary_month,O3_1988_summary_month,
                  O3_1989_summary_month,O3_1990_summary_month,O3_1991_summary_month,
                  O3_1992_summary_month,O3_1993_summary_month,O3_1994_summary_month,
                  O3_1995_summary_month,O3_1996_summary_month,O3_1997_summary_month,
                  O3_1998_summary_month,O3_1999_summary_month,O3_2000_summary_month,
                  O3_2001_summary_month,O3_2002_summary_month,O3_2003_summary_month,
                  O3_2004_summary_month,O3_2005_summary_month,O3_2006_summary_month,
                  O3_2007_summary_month,O3_2008_summary_month,O3_2009_summary_month,
                  O3_2010_summary_month,O3_2011_summary_month,O3_2012_summary_month,
                  O3_2013_summary_month,O3_2014_summary_month,O3_2015_summary_month,
                  O3_2016_summary_month,O3_2017_summary_month,O3_2018_summary_month)


colnames(O3_total_year) <- c("Site.Name", "Year", "MeanAQI")
colnames(O3_total_month) <- c("Site.Name","Month", "Year", "MeanAQI")

O3_total_year_processed <- O3_total_year %>%
  filter(Site.Name != "SITE IS LOCATED ONE HALF MILE EAST OF THE I-57/I-60 INTERCHANGE") %>%
  filter(Site.Name != "SB25 trailer at Hollenbeck School") %>%
  filter(Site.Name != "Santa Clarita-Honby St.") %>%
  filter(Site.Name != "Wilmington-N. Mahar Ave") %>%
  filter(Site.Name != "Palmdale-East Ave S") %>%
  filter(Site.Name != "Lebec") %>%
  filter(Site.Name != "West Los Angeles-Robertson Blvd") 

O3_total_month_processed <- O3_total_month %>%
  filter(Site.Name == "Los Angeles-North Main Street") %>%
  filter(Site.Name == "Lynwood") %>%
  filter(Site.Name == "Azusa") %>%
  filter(Site.Name == "Burbank") %>%
  filter(Site.Name == "Reseda") 

```

```{r exploratory tests}
qqnorm(O3_total_processed$MeanAQI)
qqline(O3_total_processed$MeanAQI)

shapiro.test(O3_total_processed$MeanAQI)
```

```{r plot processed data}
ggplot(O3_total_year_processed, aes(x = Year, y = MeanAQI)) +
  geom_point() +
  scale_y_discrete() +
  labs(y = "Mean Annual AQI Values", x = "Year")

ggplot(O3_total_month_processed, aes(x = Year, y = MeanAQI)) +
  geom_point() +
  scale_y_discrete() +
  labs(y = "Mean Annual AQI Values", x = "Year")
```

```{r autocorrelation}
O3.auto <- lme(data = O3_total_processed,
                    MeanAQI ~ Site.Name, 
                     random = ~1|Year)
O3.auto
ACF(O3.auto)
```

```{r mixed model}
class(O3_total_processed$MeanAQI)
class(O3_total_processed$Year)
class(O3_total_processed$Site.Name)

O3.mixed <- lme(data = O3_total_processed,
                     MeanAQI ~ Site.Name, 
                     random = ~1|Year,
                     method = "REML")

O3.fixed <- gls(data = O3_total_processed,
                    MeanAQI ~ Site.Name, 
                    method = "REML")

summary(O3.mixed)
summary(O3.fixed)
anova(O3.mixed,O3.fixed)

O3.posthoc = lsmeans(O3.mixed, ~ Site.Name)
cld(O3.posthoc, alpha = 0.05, Letters = letters, adjust = "tukey")
```

```{r mann-kendal tests}
mk.test(O3_total_year_processed$MeanAQI)

pettitt.test(O3_total_year_processed$MeanAQI) #at 169

mk.test(O3_total_year_processed$MeanAQI[1:168])
mk.test(O3_total_year_processed$MeanAQI[169:488])

pettitt.test(O3_total_year_processed$MeanAQI[169:488]) #at 169 + 92

mk.test(O3_total_year_processed$MeanAQI[169:260])
mk.test(O3_total_year_processed$MeanAQI[261:488])

pettitt.test(O3_total_year_processed$MeanAQI[261:488]) #no longer significant



mk.test(O3_total_month_processed$MeanAQI)

pettitt.test(O3_total_month_processed$MeanAQI) #change point at 1969

mk.test(O3_total_month_processed$MeanAQI)

```

```{r plot data with break points}
AQI.Plot.month <- ggplot(O3_total_month_processed, aes(x = Year, y = MeanAQI)) +
  geom_rect(xmin = 1978, xmax = 2020, ymin = 0, ymax = 50, fill = "darkolivegreen1", alpha = 0.1) +
  geom_rect(xmin = 1978, xmax = 2020, ymin = 51, ymax = 100, fill = "khaki1", alpha = 0.1) +
  geom_rect(xmin = 1978, xmax = 2020, ymin = 101, ymax = 150, fill = "tan1", alpha = 0.1) +
  geom_rect(xmin = 1978, xmax = 2020, ymin = 151, ymax = 200, fill = "red", alpha = 0.1) +
  geom_point(  size = 1) +
  scale_color_manual(values = c("magenta3", "violetred1", "turquoise4", "tomato3", "thistle3")) +
  #geom_vline(aes(xintercept = as.numeric("1995")), color = "black", linetype = 2) +
  #geom_vline(aes(xintercept = as.numeric("2002")), color = "black", linetype = 2) +
  labs(title = "Ozone Concentration in Los Angeles County 1980-2018", y = "Mean Annual AQI Values", color = "Sites")


print(AQI.Plot.month)

AQI.Plot.year <- ggplot(O3_total_year_processed, aes(x = Year, y = MeanAQI)) +
  geom_rect(xmin = 1978, xmax = 2020, ymin = 0, ymax = 50, fill = "darkolivegreen1", alpha = 0.1) +
  geom_rect(xmin = 1978, xmax = 2020, ymin = 51, ymax = 100, fill = "khaki1", alpha = 0.1) +
  geom_rect(xmin = 1978, xmax = 2020, ymin = 101, ymax = 150, fill = "tan1", alpha = 0.1) +
  geom_point(aes(color = Site.Name), size = 1.5) +
  scale_color_manual(values = c("magenta3", "violetred1", "turquoise4", "tomato3", "thistle3", 
                                "navy", "steelblue3", "springgreen4", "slategray3", "slateblue", 
                                "skyblue3", "sienna1", "seagreen", "dimgray", "royalblue", "rosybrown", 
                                "red3", "purple3", "brown4", "palevioletred3")) +
  #geom_vline(aes(xintercept = as.numeric("1995")), color = "black", linetype = 2) +
  #geom_vline(aes(xintercept = as.numeric("2002")), color = "black", linetype = 2) +
  labs(title = "Ozone Concentration in Los Angeles County 1980-2018", y = "Mean Annual AQI Values", color = "Sites")


print(AQI.Plot.year)
```

```{r spatial mapping}
O3_1980_spatial_summary <- O3_1980 %>%
  mutate(Year = year(O3_1980$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year, SITE_LATITUDE, SITE_LONGITUDE) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_1990_spatial_summary <- O3_1990 %>%
  mutate(Year = year(O3_1990$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year, SITE_LATITUDE, SITE_LONGITUDE) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2000_spatial_summary <- O3_2000 %>%
  mutate(Year = year(O3_2000$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year, SITE_LATITUDE, SITE_LONGITUDE) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2010_spatial_summary <- O3_2010 %>%
  mutate(Year = year(O3_2010$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year, SITE_LATITUDE, SITE_LONGITUDE) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))
O3_2018_spatial_summary <- O3_2018 %>%
  mutate(Year = year(O3_2018$Date)) %>%
  filter(DAILY_AQI_VALUE != ".") %>%
  filter(Site.Name != "") %>%
  group_by(as.character(Site.Name), Year, SITE_LATITUDE, SITE_LONGITUDE) %>%
  summarise(MeanAQI = mean(as.numeric(DAILY_AQI_VALUE)))

colnames(O3_1980_spatial_summary) <- c("Site.Name", "Year","SITE_LATITUDE", "SITE_LONGITUDE", "MeanAQI")
colnames(O3_1990_spatial_summary) <- c("Site.Name", "Year","SITE_LATITUDE", "SITE_LONGITUDE", "MeanAQI")
colnames(O3_2000_spatial_summary) <- c("Site.Name", "Year","SITE_LATITUDE", "SITE_LONGITUDE", "MeanAQI")
colnames(O3_2010_spatial_summary) <- c("Site.Name", "Year","SITE_LATITUDE", "SITE_LONGITUDE", "MeanAQI")
colnames(O3_2018_spatial_summary) <- c("Site.Name", "Year","SITE_LATITUDE", "SITE_LONGITUDE", "MeanAQI")

mapviewOptions(basemaps = c('OpenStreetMap','Esri.WorldImagery','Stamen.Toner','Stamen.Watercolor'))

O3_1980_spatial_summary_sf <- st_as_sf(O3_1980_spatial_summary,coords = c('SITE_LONGITUDE','SITE_LATITUDE'),crs=4326)
O3_1990_spatial_summary_sf <- st_as_sf(O3_1990_spatial_summary,coords = c('SITE_LONGITUDE','SITE_LATITUDE'),crs=4326)
O3_2000_spatial_summary_sf <- st_as_sf(O3_2000_spatial_summary,coords = c('SITE_LONGITUDE','SITE_LATITUDE'),crs=4326)
O3_2010_spatial_summary_sf <- st_as_sf(O3_2010_spatial_summary,coords = c('SITE_LONGITUDE','SITE_LATITUDE'),crs=4326)
O3_2018_spatial_summary_sf <- st_as_sf(O3_2018_spatial_summary,coords = c('SITE_LONGITUDE','SITE_LATITUDE'),crs=4326)

O3_spatial_total <- rbind(O3_1980_spatial_summary_sf,
                          O3_2018_spatial_summary_sf)

mapview(O3_1980_spatial_summary_sf, zcol = "Site.Name", cex = "MeanAQI")
mapview(O3_2018_spatial_summary_sf, zcol = "Site.Name", cex = "MeanAQI")
mapview(O3_spatial_total, zcol = "Year", cex = "MeanAQI")

```

