# EPA Air Quality Datasets

## Summary
This dataset was prepared for a research project for the Environmental Data Analytics (ENV 872L) at the Nicholas School of
the Environment at Duke University, April 2019

The dataset contains data from air quality monitoring of Ozone in Los Angeles County, CA from 1980-2018.

## Database Information

Data were collected using the Doanload Daily Data tool (https://www.epa.gov/outdoor-air-quality-data/download-daily-data).
The following selections were made: 
* Ozone (Air Pollutant)
* 1980-2018 (Years)
* Los Angeles County, CA (Geographic Location)
* Download CSV (spreadsheet)


csv files were saved as:'EPAair_O3_LosAngeles1980_Raw.csv',
'EPAair_O3_LosAngeles1981_Raw.csv','EPAair_O3_LosAngeles1982_Raw.csv',
'EPAair_O3_LosAngeles1983_Raw.csv','EPAair_O3_LosAngeles1984_Raw.csv',
'EPAair_O3_LosAngeles1985_Raw.csv','EPAair_O3_LosAngeles1986_Raw.csv',
'EPAair_O3_LosAngeles1987_Raw.csv','EPAair_O3_LosAngeles1988_Raw.csv',
'EPAair_O3_LosAngeles1989_Raw.csv','EPAair_O3_LosAngeles1990_Raw.csv',
'EPAair_O3_LosAngeles1991_Raw.csv','EPAair_O3_LosAngeles1992_Raw.csv',
'EPAair_O3_LosAngeles1993_Raw.csv','EPAair_O3_LosAngeles1994_Raw.csv',
'EPAair_O3_LosAngeles1995_Raw.csv','EPAair_O3_LosAngeles1996_Raw.csv',
'EPAair_O3_LosAngeles1997_Raw.csv','EPAair_O3_LosAngeles1998_Raw.csv',
'EPAair_O3_LosAngeles1999_Raw.csv','EPAair_O3_LosAngeles2000_Raw.csv',
'EPAair_O3_LosAngeles2001_Raw.csv','EPAair_O3_LosAngeles2002_Raw.csv',
'EPAair_O3_LosAngeles2003_Raw.csv','EPAair_O3_LosAngeles2004_Raw.csv',
'EPAair_O3_LosAngeles2005_Raw.csv','EPAair_O3_LosAngeles2006_Raw.csv',
'EPAair_O3_LosAngeles2007_Raw.csv','EPAair_O3_LosAngeles2008_Raw.csv',
'EPAair_O3_LosAngeles2009_Raw.csv','EPAair_O3_LosAngeles2010_Raw.csv',
'EPAair_O3_LosAngeles2011_Raw.csv','EPAair_O3_LosAngeles2012_Raw.csv',
'EPAair_O3_LosAngeles2013_Raw.csv','EPAair_O3_LosAngeles2014_Raw.csv',
'EPAair_O3_LosAngeles2015_Raw.csv','EPAair_O3_LosAngeles2016_Raw.csv',
'EPAair_O3_LosAngeles2017_Raw.csv','EPAair_O3_LosAngeles2018_Raw.csv'

Data were accessed 2019-03-21.

## Data Content Information
Information gathered from: https://www.epa.gov/outdoor-air-quality-data/air-data-basic-information and https://aqs.epa.gov/aqsweb/documents/AQS_Format.html


Date: month/day/year
Source: AQS (Air Quality System) or AirNow
Site ID: A unique number within the county identifying the site.
POC: “Parameter Occurrence Code” used to distinguish different instruments that measure the same parameter at the same site.
Daily Max 8-hour Ozone Concentration: numeric value
Units: units for concentration

Daily_AQI_VALUE: Air quality index (range 0-500). Levels: 
0-50: Good (green)
51-100: Moderate (yellow)
101-150: Unhealthy for sensitive groups (orange)
151-200: Unhealthy (red)
201-300: Very unhealthy (purple)
301-500: Hazardous (maroon)

Site Name
DAILY_OBS_COUNT: number of observations per day
PERCENT_COMPLETE
AQS_PARAMETER_CODE
AQS_PARAMETER_DESC
CBSA_CODE
CBSA_NAME
STATE_CODE
STATE
COUNTY_CODE
COUNTY
SITE_LATITUDE
SITE_LONGITUDE

## Naming conventions and file formats
Files are named according to the following naming convention: `databasename_dataname_details_stage.format`, where: 

**databasename** refers to the original database

**dataname** is a description of data 

**details** are additional details describing the data, which are important for processed data files

**stage** refers to the stage of data management (raw, cleaned, or processed)

**format** is the file format (.csv, .txt, xlsx, etc.)

## Additional Information and Support
For additional information, please contact Lindsay Roth (lindsay.roth@duke.edu), the assembler of the data